### ISSUE TITLE
One alternative

### ISSUE THREAD

**Issue by lucarin91** [PisaCoderDojo/JavaScript-Lessons#1]
Io metterei una sola versione di ogni "comando"

[Qui](https://github.com/PisaCoderDojo/JavaScript-Lessons/blob/3ba2d5926238bebc4a3fcdff8e5d4ec843f252fe/fondamenti.js#L38-L39) lascerei solo `"Pisa"[1]`.

**Comment by Ventrosky** [comment]
tolto .charAt()
