### ISSUE TITLE
bug lovercase

### ISSUE THREAD

**Issue by lucarin91** [PisaCoderDojo/JavaScript-Lessons#2]
[Qui](https://github.com/PisaCoderDojo/JavaScript-Lessons/blob/3ba2d5926238bebc4a3fcdff8e5d4ec843f252fe/fondamenti.js#L43) c'è un errore dovrebbe essere `"CoderDojo Pisa".toLowerCase();`

**Comment by Ventrosky** [comment]
fix copypaste
